//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtutOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblogrencı
    {
        public int id { get; set; }
        public string adsoyad { get; set; }
        public string tc { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
        public string ders { get; set; }
        public string sınıf { get; set; }
    }
}
